- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Creates directory
      file:
       path: "{{ item }}"
       state: directory
      with_items:
          - /tmp/www
          - /tmp/foo
          - /tmp/bar
        
