- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Show disk space
      file:
        path: /tmp/welcome
        state: directory
