- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Creates directory
      file:
        path: /tmp
        state: directory
        mode: 0777
        
