---
- name: This sets up an httpd webserver
  hosts: all
  become: yes
  tasks:
  - name: Install apache packages
    yum:
      name: httpd
      state: latest
  - name: enable and start Apache server
    service:
       name: httpd
       enabled: yes
       state: started
 
